# Generated by Django 6.0.5 on 2026-05-18 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='image',
            field=models.URLField(blank=True, max_length=1000),
        ),
    ]
