# Generated by Django 6.0.5 on 2026-05-20 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('destination', models.CharField(max_length=255)),
                ('price', models.CharField(max_length=50)),
                ('rating', models.FloatField(default=4.5)),
                ('stay_type', models.CharField(choices=[('hotel', 'Luxury Hotel'), ('camp', 'Night Camp')], default='hotel', max_length=10)),
                ('image', models.URLField(max_length=500)),
            ],
        ),
    ]
