# Generated by Django 6.0.5 on 2026-05-19 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Itinerary', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='itinerary',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
