# Generated by Django 6.0.5 on 2026-05-19 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Itinerary', '0002_itinerary_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='itinerary',
            name='destination_image',
            field=models.URLField(blank=True, null=True),
        ),
    ]
