# Generated by Django 6.0.5 on 2026-05-26 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Itinerary', '0003_itinerary_destination_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='itinerary',
            name='accommodation_data',
            field=models.JSONField(blank=True, help_text='Stores RAG-retrieved hotel/activity recommendations', null=True),
        ),
        migrations.AddField(
            model_name='itinerary',
            name='ai_model_version',
            field=models.CharField(default='gemini-1.5-flash', max_length=50),
        ),
    ]
