# Generated by Django 6.0.5 on 2026-05-26 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Itinerary', '0004_itinerary_accommodation_data_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itinerary',
            name='accommodation_data',
        ),
        migrations.RemoveField(
            model_name='itinerary',
            name='ai_model_version',
        ),
        migrations.AddField(
            model_name='itinerary',
            name='ai_model',
            field=models.CharField(default='gemini-2.5-flash', max_length=100),
        ),
        migrations.AlterField(
            model_name='itinerary',
            name='destination_image',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
    ]
