# Generated by Django 6.0.5 on 2026-05-26 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Itinerary', '0005_remove_itinerary_accommodation_data_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itinerary',
            name='destination_image',
            field=models.URLField(blank=True, null=True),
        ),
    ]
